version: "3.2"
services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  backend-api:
    build: 
      context: ./backend-api
      dockerfile: ../backend-api.dockerfile
    depends_on:
      - redis
    ports:
      - "8081:80"
  frontend-api:
    env_file: ./frontend-api/.env.production
    build: 
      context: ./frontend-api
      dockerfile: ../frontend-api.dockerfile
    depends_on:
      - backend-api
      - redis
    ports:
      - "8080:8080"
  frontend-app:
    env_file: ./frontend-app/.env.ssr
    build: 
      context: ./frontend-app
      dockerfile: ../frontend-app.dockerfile
    depends_on:
      - frontend-api
    ports:
      - "3000:3000"